### ISSUE TITLE
fullText parameter for Facets?

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#11]
I was wondering if it would be possible to return facets based on the entered keyword (fullText)?
Right now we get a list of facets based on the filter parameters and this is great!

But we'd like to get even more precise facets by adding the fulltext parameter. Otherwise it's possible for our clients to end up on pages with no article results (since the fullText parameter is ruling them out via the Articles API).

Thanks

**Comment by jukey** [comment]
Hi @cschalenborgh,

thanks for your request. It could happen that we implement this feature in the future but there is no concrete plan when this might happen.

Cheers Uwe

**Comment by jukey** [comment]
Currently we do not plan to implement this feature.
