### ISSUE TITLE
Duplicate displayName's in Facets

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#12]
See https://api.zalando.com/facets
The Facets API sometimes returns duplicate displayName's. Can Zalando do something about this?

<img width="393" alt="screen shot 2015-11-21 at 23 59 36" src="https://cloud.githubusercontent.com/assets/10864861/11320985/f3ba489c-90ae-11e5-96a7-3d3dd6bd8e28.png">

Thanks

**Comment by jukey** [comment]
HI @cschalenborgh,

thanks for reporting this. We need to investigate this issue and come back to you.

Cheers Uwe

**Comment by cschalenborgh** [comment]
Any news on this?

**Comment by jukey** [comment]
Sorry, but this behavior is not going to change in the foreseeable future.
