### ISSUE TITLE
Color "grey" does not work

### ISSUE THREAD

**Issue by Jan-M** [zalando/shop-api-documentation#13]
I was told during last hackathon.

**Comment by mostlymagic** [comment]
The key is "gray". See https://api.zalando.com/filters

**Comment by Jan-M** [comment]
https://github.com/zalando/shop-api-documentation/wiki/Articles

this points to "grey"

**Comment by Jan-M** [comment]
and I believe it did in some cases still not work as I was told ;) this is obvious try grey/gray

**Comment by jukey** [comment]
Hi Jan,

I changed the documentatin. It's gray now:
https://github.com/zalando/shop-api-documentation/wiki/Articles

However you always can check which filters and filter values are available using:
https://api.zalando.com/facets or
https://api.zalando.com/filters

**Comment by Jan-M** [comment]
https://api.zalando.com/articles?color=gray

yields in first article: 

"color" : "Grey"

"id" : "H2741E000-C11"

:D

**Comment by jukey** [comment]
Default app domain is UK, where "grey" is fine. Try another like:

```
curl -X GET --header "Accept: application/json" --header "Accept-Language: de-DE" --header "x-client-name: api-swagger-ui" "https://api.zalando.com/articles
```

and you will get colors in German.

**Comment by Jan-M** [comment]
There is so much nice magic at work :-)

Thx for looking into this, will stop bothering you now.
