### ISSUE TITLE
Some keywords in documentation still use camelCase and do not work

### ISSUE THREAD

**Issue by Jan-M** [zalando/shop-api-documentation#14]
Also hackweek feedback. Told them to switch to underscore writing, believe that helped.

**Comment by jukey** [comment]
Please provide concrete examples. Thanks Uwe

**Comment by Jan-M** [comment]
https://github.com/zalando/shop-api-documentation/wiki/Articles

Lots of key word references to camel cases.

I am sorry I don't have the real example anymore, I know this is not the best feedback ;) but maybe you know the issue.

Or as Sean did maybe you can reference "api links" that auto generate the options.

**Comment by mostlymagic** [comment]
camelCase is used because this API was implemented long before we had a guideline that said otherwise. Changing that would break existing clients, which would also violate our API guidelines.

I fail to see any example where the documentation is inconsistent with the actual markup.
