### ISSUE TITLE
Sorting issue @ facets API

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#15]
See https://api.zalando.com/facets and enclosed screenshot (locale = nl-BE). They seem to be sorted by 'key' instead of 'displayName'? Is there a way to overwrite the default sorting of facet values?

![screen shot 2015-12-02 at 10 02 43](https://cloud.githubusercontent.com/assets/10864861/11526624/f40efeac-98db-11e5-847f-7c44953f7cb0.png)

**Comment by jukey** [comment]
Hi @cschalenborgh,

currently we do not offer another way to sort this kind of response.

However I am going to add this as a feature request to the backlog in order to see if we can make it happen.

cheers Uwe

**Comment by jukey** [comment]
We do not have plans to implement this feature.
