### ISSUE TITLE
Sorting issue @ units API

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#16]
See https://api.zalando.com/articles/C1181A00F-Q11/units
There's no size sorting (for example small > big) like on https://www.zalando.be/calvin-klein-underwear-modern-cotton-t-shirt-bh-zwart-c1181a00f-q11.html. Can this be implemented? Currently all the units are randomly mixed together it seems.

![screen shot 2015-12-23 at 14 59 56](https://cloud.githubusercontent.com/assets/10864861/11977767/1002b706-a986-11e5-9a79-611c01866f91.png)

**Comment by jukey** [comment]
There are currently no plans to do this, sorry.
