### ISSUE TITLE
Please clarify license situation for API responses

### ISSUE THREAD

**Issue by daniel-j-h** [zalando/shop-api-documentation#17]
I read the Wiki and looked around on the internet but wasn't able to find the terms under which the API responses are licensed.

- What am I allowed to do with the responses?
- What am I allowed to do with user reviews?
- What am I allowed to do with the images for which I get URLs?
- Can I permanently store responses or just temporarily?

I could not find answers to these and similar important questions. Would you be so kind and clarify this, and maybe also document it in your Wiki?

**Comment by hjacobs** [comment]
@daniel-j-h yes, I think these are important questions :smile: 

Maybe @jukey or @ThorbjoernG can clarify these...

**Comment by daniel-j-h** [comment]
Any updates here, too? This is blocking me playing around with it on rainy weekends. And it looks like we're going to have a bunch of those coming up :)

**Comment by hjacobs** [comment]
Bumping this too -> @jukey @ThorbjoernG

**Comment by jukey** [comment]
I contacted Daniel via mail directly.
