### ISSUE TITLE
Please clarify usage terms for accessing the API

### ISSUE THREAD

**Issue by daniel-j-h** [zalando/shop-api-documentation#18]
I could not find anything about this on the Wiki. What are the API's usage terms?

- Is there a rate limiting regarding API requests?
- Is there a limit for accessing images for which I get URLs?
- Do I have to set the User-Agent (e.g. to something sensible you can act upon)?
- Is politely crawling with timeouts allowed?

Please clarify these and other questions, and maybe document them in your Wiki.

**Comment by jukey** [comment]
I am going to take care to get the right answers to the valid questions you asked. @daniel-j-h.

**Comment by daniel-j-h** [comment]
Any updates here?

**Comment by jukey** [comment]
check you mails please.

**Comment by Limmen** [comment]
Is the terms of use published somewhere or could I get information by email as well? kimham@kth.se
Thanks.
BR

**Comment by duergner** [comment]
@Limmen please get in contact with us via https://build.zalando.com
