### ISSUE TITLE
Outdated information on article. The API does not use SKU anymore but id. 

### ISSUE THREAD

**Issue by skarab7** [zalando/shop-api-documentation#2]
The current version of API does not provide *SKU* but uses *ID* for identifying articles, e.g.:

```bash
curl https://api.zalando.com/articles\?page\=2\&size\=1

...
    "id" : "4BE23C048-L11",
    "modelId" : "4BE23C048",
    "name" : "Shorts - hellblau",
    "shopUrl" : "http://www.zalando.co.uk/benetton-shorts-blue-4be23c048-l11.html",
    "color" : "Blue",
    "available" : true,
...
```

The zalando API wiki does not reflect this change:

https://github.com/zalando/shop-api-documentation/wiki/Articles#sku

**Comment by skarab7** [comment]
Hi Valgog, if it is a question for me, I do not know ;). SKU sounds much cooler than ID.

**Comment by benjaminwagner** [comment]
SKU (as in stock keeping unit) should represent the distinct item that can be added to a shopping cart, but this is not the case for article.sku. Its only possible to order an article.unit.  

We didn't wanted to confuse everybody by having an articleSKU, an articleUnitSKU and an articleModelSKU, thats why we decided to replace SKU by Id.
