### ISSUE TITLE
Accept-Language is not working 

### ISSUE THREAD

**Issue by prakashmalviya** [zalando/shop-api-documentation#20]
I want to set language de-DE.
I have tried cURL, file_get_content but both are not working for me. Even in cURL i am not getting any response.

**Comment by jukey** [comment]
Please share your curl statement and the response. Thanks.

**Comment by arekdziewonski** [comment]
It won't change the language the API uses, but it will display articles available in a shop for selected country/language, like de-DE for http://www.zalando.de, nl-BE for http://www.zalando.be and fr-BE for http://fr.zalando.be

**Comment by prakashmalviya** [comment]
`$import_lang = '';
$import_header = $import_lang == 'en' ? 'en-GB' : 'de-DE';
            $request_url = 'https://api.zalando.com/articles/?fullText=cloths';
			 $opts = array(
            'https' => array(
                'header' => 'Accept-Language: de-DE'
            )
        );
        print_r($opts);
        $context = stream_context_create($opts);		
        $response = file_get_contents($request_url, false, $context);
        echo '<pre>';
        print_r($response);
        exit;`


`$ch = curl_init();
        curl_setopt($ch, CURLOPT_PROTOCOLS, CURLPROTO_HTTPS);    
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, false);
        curl_setopt($ch, CURLOPT_URL, $request_url);   
        $headers = array();
        $headers[] = 'Accept-Language: ' . $import_lang;
        $headers[] = 'Cache-Control: no-cache';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $server_output = curl_exec($ch);

        curl_close($ch);
        echo '<pre>';
        print $server_output;`

For cURL response is empty and for file_get_content response in en-GB only.

**Comment by prakashmalviya** [comment]
Any suggestions ?

**Comment by prakashmalviya** [comment]
`$import_lang = '';
		$import_header = $import_lang == 'en' ? 'en-GB' : 'de-DE';
		$request_url = 'https://api.zalando.com/articles/?fullText=cloths';
		$ch = curl_init();
        curl_setopt($ch, CURLOPT_PROTOCOLS, CURLPROTO_HTTPS);    
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_URL, $request_url);   
        $headers = array();
        $headers[] = 'Accept-Language: ' . $import_header;
        $headers[] = 'Cache-Control: no-cache';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $server_output = curl_exec($ch);
        curl_close($ch);
        echo '<pre>';
        print $server_output;
        exit;`

Above is the working code for me !!!

**Comment by prakashmalviya** [comment]
To avoid header just set below option 
curl_setopt($ch, CURLOPT_HEADER, false);

**Comment by jukey** [comment]
Hi, it would be nice if you pass a complete curl statement like this one:
```
curl -X GET --header "Accept: application/json" --header "Accept-Language: de-DE" --header "x-client-name: api-swagger-ui" "https://api.zalando.com/articles"
```
For the statement above you get articles from the German Zalando website containing german descriptions:
```
{
  "content" : [ {
    "id" : "OP521N000-K11",
    "modelId" : "OP521N000",
    "name" : "ALVA - Jeans Skinny Fit - midnight sky wash",
    "shopUrl" : "https://www.zalando.de/marc-o-polo-denim-alva-jeans-slim-fit-midnight-sky-wash-op521n000-k11.html",
    "color" : "Blau",
    "available" : true,
    "season" : "SUMMER",
    "seasonYear" : "2016",
    "activationDate" : "2016-01-18T19:57:34+01:00",
    "additionalInfos" : [ "Echtleder Labelpatch am Hosenbund", "kleine Echtleder Labelschlaufe an der Gesäßtasche", "Used Look", "Destroyed-Effekte" ],

[...]
```
Does this answer your initial question?
