### ISSUE TITLE
Pagination behavior in article-reviews endpoint

### ISSUE THREAD

**Issue by daniel-j-h** [zalando/shop-api-documentation#21]
Hey hey, since yesterday I started playing around with the API. So far I found the following issue with the `article-reviews` endpoint. As per [the Wiki on Pagination](https://github.com/zalando/shop-api-documentation/wiki/Api-introduction#pagination) let's request the first page and see how many pages there are for our `pageSize=100`:

```json
$ http --body 'https://api.zalando.com/article-reviews?page=1&pageSize=100' 'Accept-Language:de-DE' 'Accept-Encoding:gzip' 'x-client-name:ClassyShoes' | jq 'del(.content)'
{
  "totalElements": 2590134,
  "totalPages": 25902,
  "page": 1,
  "size": 100
}
```

Let's try to get the last page `25902` then:

```json
$ http --body 'https://api.zalando.com/article-reviews?page=25902&pageSize=100' 'Accept-Language:de-DE' 'Accept-Encoding:gzip' 'x-client-name:ClassyShoes' | jq 'del(.content)'
{
  "totalElements": 0,
  "totalPages": 0,
  "page": 1,
  "size": 0
}
```

(for the record, this ^ request takes ~10s before returning)

Hm might be related to the last page? Let's take a look at a page way before:

```json
$ http --body 'https://api.zalando.com/article-reviews?page=25000&pageSize=100' 'Accept-Language:de-DE' 'Accept-Encoding:gzip' 'x-client-name:ClassyShoes' | jq 'del(.content)'
{
  "totalElements": 0,
  "totalPages": 0,
  "page": 1,
  "size": 0
}
```

(this ^ request returns instantly, but response is not what I expected)

I can not reproduce this behavior with the `articles` endpoint. Any ideas on this?

**Comment by daniel-j-h** [comment]
For the record, I need those reviews for my little Easter side-project I started a few days ago:

https://github.com/daniel-j-h/classyshoes

In which I train a Paragraph Vector model on reviews and article ids in order to 1/ generate feature vectors from reviews for further classification and 2/ infer new paragraph vectors based on user preferences and queries. The idea for the latter is for users to be able to formulate queries similar to "summer dress pregnancy" and get articles that have _semantically_ similar reviews.

At the time of writing this, the API responds with `2.594.799` total elements in the first page response, but I can only get `151.100` reviews due to the behavior described above.

**Comment by daniel-j-h** [comment]
For the record, I can still reproduce the issue as of today.


Initial query for getting total pages:

```json
$ http --body 'https://api.zalando.com/article-reviews?page=1&pageSize=100' 'Accept-Language:de-DE' 'Accept-Encoding:gzip' 'x-client-name:ClassyShoes' | jq 'del(.content)'
{
  "totalElements": 2605127,
  "totalPages": 26052,
  "page": 1,
  "size": 100
}
```

Querying last page (this takes ~10 seconds until I get a response, and the response is invalid):

```json
$ http --body 'https://api.zalando.com/article-reviews?page=26052&pageSize=100' 'Accept-Language:de-DE' 'Accept-Encoding:gzip' 'x-client-name:ClassyShoes' | jq 'del(.content)'
{
  "totalElements": 0,
  "totalPages": 0,
  "page": 1,
  "size": 0
}
```

Querying a page a somewhat before the last page (here I'm getting the response instantly, still invalid):

```json
$ http --body 'https://api.zalando.com/article-reviews?page=25000&pageSize=100' 'Accept-Language:de-DE' 'Accept-Encoding:gzip' 'x-client-name:ClassyShoes' | jq 'del(.content)'
{
  "totalElements": 0,
  "totalPages": 0,
  "page": 1,
  "size": 0
}
```

**Comment by jukey** [comment]
Hi Daniel,

the Zalando Public API currently is in a maintenance mode. That means there is no feature development and bug fixing just in case there is a business demand. This might be changed again in the future but as I said currently there are no plans.

You might use the API for your analysis project but I cannot promise that bugs (like you reported) are fixed.

In case you would like to turn your project into a commercial one you can contact me in order to connect you the right people. Currently most of our partners are not using the API but huge files containing all article data (but I am not sure about reviews).

Cheers Uwe
