### ISSUE TITLE
cskus missing

### ISSUE THREAD

**Issue by georghildebrand** [zalando/shop-api-documentation#22]
Hi,

i have a list of about 12000 cskus. My goal is to get the premium image urls of the model front model shots (i want to build a DNN do distinguish garment types).

I am downloading the article data im chunks of 199. 
But what i realized is that it returns only a few articles. Could it be, that the api holds only live articles?
Here is one example request that returns only 88 articles...
thx a lot in andvance!.

https://api.zalando.com/articles?articleId=SU222P01O-G11&articleId=TO222O01U-G11&articleId=ON321D0MN-A11&articleId=ES124G074-G11&articleId=QS121D0B9-Q11&articleId=SE622D0IV-K11&articleId=QU122D04V-G11&articleId=JA222O0QV-C11&articleId=P3222D02O-A11&articleId=PE122O017-K11&articleId=CL823G00B-A11&articleId=JA222D10J-Q11&articleId=JA222D0VX-K12&articleId=N1423G030-G11&articleId=TO223G03N-A11&articleId=ZS322D011-K12&articleId=VE121E0DL-Q11&articleId=GA322E00J-I11&articleId=AJ122O01V-A11&articleId=ED121D0DI-J11&articleId=GA322D00E-002&articleId=PO222D08U-J11&articleId=RE321D03U-A11&articleId=BI724G010-Q11&articleId=EV421D0HC-A11&articleId=ES124G06K-Q11&articleId=EV421DA3F-A11&articleId=4AP21D037-C11&articleId=JA222O0KL-C11&articleId=MV224G00Q-K11&articleId=SU222P00W-Q11&articleId=EV421DA1A-Q11&articleId=4BE24G05S-C11&articleId=LE122O01T-K11&articleId=TO722O06C-A11&articleId=VA221D03A-B11&articleId=OK023G00M-C11&articleId=JA222O0T3-A11&articleId=CO422O00I-A11&articleId=TO221D07Z-G11&articleId=WF521D005-N11&articleId=RO521D062-A11&articleId=AR321D02O-Q11&articleId=AN621D0AR-J11&articleId=OS322O040-C11&articleId=OB121D06E-H11&articleId=NI122O03K-C11&articleId=GU121D0A1-A11&articleId=MG021D00V-A11&articleId=DC124G00Z-G11&articleId=EQ121E00X-A11&articleId=SK021D000-K12&articleId=TO722O04R-A12&articleId=TF121E000-Q11&articleId=OL822D04G-K11&articleId=S8521D0SX-Q11&articleId=EV421DA2Y-C11&articleId=MF921D023-Q11&articleId=SO222O02K-C11&articleId=TS122O00V-Q11&articleId=TO722O077-G11&articleId=MK922O00F-K11&articleId=DM124D002-802&articleId=ES421E04R-A11&articleId=TO722O05Z-G11&articleId=SO921E01G-A11&articleId=PO222D08U-J12&articleId=M0822O04T-C11&articleId=PO222O018-A11&articleId=PE621D03N-A11&articleId=ON321D0PG-C11&articleId=GA321E03J-G11&articleId=NA622P00Y-G11&articleId=TE422P00D-K12&articleId=JA222O0CB-Q11&articleId=AM221D04L-Q11&articleId=ON321D0LC-Q11&articleId=JA222O0G7-Q11&articleId=SU222O0DW-M11&articleId=AM221D04C-A11&articleId=GP021D016-C11&articleId=GP022O01G-C11&articleId=NN121E02W-K11&articleId=ME422P000-A11&articleId=GP021D02A-K11&articleId=DP521D05P-T11&articleId=DI121D067-J11&articleId=V1021E063-J11&articleId=SO221D0IY-J11&articleId=SU222O0ET-G11&articleId=S8521D0RS-C11&articleId=JR421D04H-O11&articleId=MF921D011-K11&articleId=JA222O0E3-C12&articleId=DP521D03N-J11&articleId=L7721D00P-A11&articleId=JR421D03Z-A11&articleId=EV421D0EF-A11&articleId=JA222D0Y7-K12&articleId=KH121D05S-G11&articleId=OX522D02U-A11&articleId=NA521E035-K11&articleId=E7721E00X-C11&articleId=KH121D071-Q11&articleId=LE126G007-C11&articleId=V1021E047-Q11&articleId=S8521D0SS-J11&articleId=T1022D02D-K11&articleId=ON321E078-A12&articleId=A2322O00H-A11&articleId=DI121D053-Q11&articleId=BE623G01D-K11&articleId=NX324G01V-A11&articleId=VE121E0F4-Q11&articleId=M9121E0L4-B11&articleId=2ET22D0DU-K12&articleId=BT322O00D-C12&articleId=YO122O052-Q11&articleId=SU221D0BO-C11&articleId=TP721D034-C11&articleId=RE121E00Y-302&articleId=SU222O0AH-G11&articleId=WF524I005-A11&articleId=MK121D01Y-G11&articleId=GS221D01E-C11&articleId=JA222D10M-C11&articleId=V1021E064-Q11&articleId=RM021D00A-H11&articleId=MA322P00L-C11&articleId=M3621D043-Q11&articleId=JL121D000-A11&articleId=ES121E087-A11&articleId=CO421D03Q-C11&articleId=NX324G06I-K11&articleId=ED121D0AW-A11&articleId=BJ721D002-C11&articleId=TW421D02T-Q11&articleId=4BE24G05A-K11&articleId=LT122O00T-C11&articleId=ME421D01S-002&articleId=S3122D026-Q11&articleId=NM321D03P-K11&articleId=DP521E0B1-Q11&articleId=KH121D06A-Q11&articleId=DI622O00T-A11&articleId=ES121D0C9-A11&articleId=LE422D02R-K11&articleId=TO122D09U-K11&articleId=HY522O01N-Q11&articleId=D3021E01X-G11&articleId=TW421D04B-A11&articleId=DP521D03G-L11&articleId=M9121E0MJ-K11&articleId=L4524G04S-L11&articleId=M9122P00C-Q11&articleId=MA321D092-A11&articleId=BM821D00U-B11&articleId=NM321D04I-A12&articleId=ON321E08G-J11&articleId=H4421E04I-K11&articleId=S3621E018-G11&articleId=PO222P00X-M12&articleId=M9121E0L0-P11&articleId=BL824G01L-C11&articleId=BZ121D00A-M11&articleId=CA522P00A-K11&articleId=H4421E050-Q11&articleId=S5521D05R-K11&articleId=OK024G004-A11&articleId=SE622O051-A12&articleId=S8521E09J-A11&articleId=GS122O03Z-A11&articleId=SU221D0H1-A11&articleId=ES124G074-K11&articleId=S8521D0SL-Q11&articleId=NY222O00Q-K11&articleId=AX522O00D-A11&articleId=WL722DA01-A11&articleId=PE124G038-K11&articleId=4BE24G04V-M11&articleId=ZA821D03K-A11&articleId=GU121D08G-A11&articleId=OR322O005-K11&articleId=K4421EA11-K11&articleId=M9122D03A-K12&articleId=PO224I00R-E11&articleId=ON321D0Q3-K11&articleId=QX721E002-Q11&articleId=SP421D02B-A11&articleId=TW421DA1R-A11&articleId=Y0121D008-Q11&articleId=AN621D0AV-I11&articleId=ES121E07B-K11&articleId=VE121E09M-Q11&articleId=PI922OA0N-K11&articleId=M5921D0EU-Q11&articleId=4BE21E03P-K12&articleId=MU322O00I-A11&articleId=VM421E02R-K11&pageSize=200

**Comment by jukey** [comment]
You are right, the API just provides articles that are on stock and available via the Zalando Websites as well. For further questions feel free to contact me via hipchat.
