### ISSUE TITLE
URGENT: article endpoint returns available=false & stock=0 for every product!

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#24]
See this one for example:
https://api.zalando.com/articles/LE421C00D-K11

<img width="642" alt="screen shot 2016-08-05 at 11 03 30" src="https://cloud.githubusercontent.com/assets/10864861/17431864/63fe0b62-5afc-11e6-8fd6-9e4d90624c2a.png">

<img width="1039" alt="screen shot 2016-08-05 at 11 03 45" src="https://cloud.githubusercontent.com/assets/10864861/17431865/640144da-5afc-11e6-99f8-331e247698de.png">

I tried with at least 10 product SKU's, they are all unavailable via the API, but available on your website. Can this be fixed as soon as possible?

Thanks

**Comment by jukey** [comment]
Hi @cschalenborgh, when this appeared the first time? Today or was it also the case in past?

**Comment by cschalenborgh** [comment]
Thanks Jukey! It's working again.
