### ISSUE TITLE
Zalando confirmation mails don't have data

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#25]
See screenshot. There's no order data in the order confirmation mail (address, products, amounts, ...)

<img width="951" alt="screen shot 2016-08-09 at 02 44 33" src="https://cloud.githubusercontent.com/assets/10864861/17501029/3a398c84-5ddb-11e6-814c-a9803f67833b.png">

**Comment by hjacobs** [comment]
@cschalenborgh thanks for letting us know, this is probably not related to the Shop API Documentation (this repo), but we will look into it!

**Comment by jukey** [comment]
Should be fixed, thanks again for the report
