### ISSUE TITLE
Add EAN number to product details response

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#26]
Would it be possible to add a product's EAN code to the API output?
# https://www.zalando.be/part-two-calla-blousejurk-artwork-black-p2121c01h-a11.html
# https://api.zalando.com/articles/p2121c01h-a11

ean -> 5712437060964

Thanks

**Comment by LappleApple** [comment]
Hi @jukey @joeranriesszal @duergner, wondering if this is in the works or if we can close.
