### ISSUE TITLE
No way to get outfit recommendation

### ISSUE THREAD

**Issue by vr367305** [zalando/shop-api-documentation#29]
I'm writing an aplication using this API and i noticed that there is no way to get outfit recommendations (as in "wear it with" on the website) since the Recommendation section on the API only gives you results from the "you might like" on the website.

For example looking at this article https://www.zalando.co.uk/jack-jones-jorben-jumper-cloud-dancer-ja222q0eh-a11.html
i want to get results like this https://www.zalando.co.uk/jack-jones-jjcojade-regular-fit-tracksuit-bottoms-ja222e04e-q11.html
and not a similar product like this https://www.zalando.co.uk/jack-jones-joravenue-cardigan-light-grey-melange-ja222q0ex-c11.html

Is there something i am missing in the API or there is no way to do this?

**Comment by duergner** [comment]
@vr367305 there is no way to get outfit like recommendations using this API.
