### ISSUE TITLE
Getting 'description' from the website

### ISSUE THREAD

**Issue by sujaymansingh** [zalando/shop-api-documentation#3]
Is there a way to get the extended description that is available on the website?

For example: on the page https://www.zalando.de/garcia-cinnamon-t-shirt-print-bleached-neon-g1223g01a-g11.html there is a description:

"‚Paradise is just around the corner‘, da ist sich das T-Shirt CINNAMON von Garcia sicher und es scheint wirklich Recht zu haben. Sein Design bringt so viele tolle Details zum Vorschein, dass deine Tochter nur noch begeistert staunen dürfte. Ärmel aus Spitze, ein Glitzerprint, dekorative Nieten – dieses Streifenshirt ist ein Hit.

offener Ausschnittsaum mit Nietendekor
Ärmel aus Spitze
Frontprint mit glitzernden Palmen und Ziersteinchen
leicht verwaschener Look
Gesamtlänge: 51 cm bei Größe 140/146
Kragen: Rundhals
Passform: Fällt kleiner aus
Material Oberstoff: 70% Baumwolle, 30% Polyester
Pflegehinweise: nicht Trockner geeignet, Maschinenwäsche bei 30°C, Schonwaschgang
Artikelnummer: G1223G01A-G11"

The description lines that begin with "Paradise is just around the corner" do not exist in the API url for the article: 
```
curl -H 'Accept-Language: de-DE' 'https://api.zalando.com/articles/G1223G01A-G11'
```

How would we get that information?

**Comment by benjaminwagner** [comment]
Hi,

at Zalando we stopped adding descriptions for the articles. Only older articles still have it (like your example, which is from march of last year - see the activationDate). This is why we decided not to publish a description field on the articles with the API, since it will sooner or later always be empty.

Regards,
Benjamin

**Comment by sujaymansingh** [comment]
Ah I see, thanks @benjaminwagner
