### ISSUE TITLE
Details about API usage

### ISSUE THREAD

**Issue by alkuzad** [zalando/shop-api-documentation#33]
Hi 

I want to do App using this API but there are still vague topics in this matter:

1. How many requests per hour/day can user do. Is it bound to User-Agent or per some account ? Does it depend on site ?
2. Can I rewrite data to my own database (Elasticsearch) to use them more efficiently ? Current API only has AND operator and it does not have negation system. If yes - are there any terms for that ?
3. What is guaranteed delay between main Zalando page and API ? Is it counted in hours or minutes ?

**Comment by duergner** [comment]
Hi @alkuzad please get in touch with out business development team vi https://build.zalando.com for your questions.
