### ISSUE TITLE
Try to use oAuth2

### ISSUE THREAD

**Issue by rzanotti2** [zalando/shop-api-documentation#37]
Today Zalando Api changes, 

I am trying to use oAuth2 but it does not work, need some help please.
This is my code : 
` $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "https://api.zalando.com/oauth2/token?grant_type=client_credentials&business_partner_id=testZapato");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_USERPWD, "helloZapato:helloSecretZapato");

        $headers = array();
        $headers[] = "Accept: application/json";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }

        curl_close ($ch);

        print_r($result);`

Maybe it's a problem of url ? This is the response of the API : 
Full authentication is required to access this resource

Thanks for your answer :)

**Comment by duergner** [comment]
Please follow the steps outlined in https://github.com/zalando/shop-api-documentation/wiki/Authentication#registration

**Comment by duergner** [comment]
Once you registered on https://build.zalando.com someone from our Zalando Build will reach out to you about the exact next steps. They'll review your use case and provide you with the client_id and client_secret you need to access the API and further information about the endpoints to use to generate a OAuth2 Bearer token.

**Comment by rzanotti2** [comment]
Ok, i understand thank you for your quick reply :)
