### ISSUE TITLE
Missing value in Filter Type

### ISSUE THREAD

**Issue by GuillermoBlasco** [zalando/shop-api-documentation#4]
The wiki says that the Filter type scope is:

* range

* string

* enum

* key

But actually there is also possible the filter type value "SKU".

Also consider that all are returned from API in uppercase. Eg:

    {
        name: "articleId",
        multiValue: true,
        type: "SKU",    
        values: [ ]
    },
    {
        name: "articleModelId",
        multiValue: true,
        type: "SKU",
        values: [ ]
    },

**Comment by benjaminwagner** [comment]
Thanks for pointing this out. We updated the documentation.
