### ISSUE TITLE
PHP API wrapper

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#6]
I've written a PHP client for the Zalando API. You can find it @ https://github.com/cschalenborgh/php-zalando

Most of the API methods are implemented. A couple of filters are still missing so feel free to contribute.

**Comment by benjaminwagner** [comment]
Thanks for sharing this. We will create a section in our documentation with links to client implementations.

Its roughly 15 years ago that I  have done something with PHP, so my knowledgeis definitely outdated, but as I understand your code, you create a new Guzzle client instance for each request, right? Can you still reuse the connection or is there a new ssl negotiation for each request? Just thinking about performance and response times.

Oh, and please update your README.md:
Its /article-reviews and /article-reviews-summaries and not /article**s**-reviews....

Regards
Ben

**Comment by cschalenborgh** [comment]
Thanks Benjamin.

I've fixed the API endpoints typo in the readme.

> as I understand your code, you create a new Guzzle client instance for each request, right? Can you still reuse the connection or is there a new ssl negotiation for each request? 

That's correct. But if I'm correct cURL reuses connections by default unless this option is set:

> CURLOPT_FORBID_REUSE	TRUE to force the connection to explicitly close when it has finished processing, and not be pooled for reuse.


But it all depends on your server config because:

> Guzzle no longer requires cURL in order to send HTTP requests. Guzzle will use the PHP stream wrapper to send HTTP requests if cURL is not installed. Alternatively, you can provide your own HTTP handler used to send requests.

**Comment by jukey** [comment]
Hi @cschalenborgh,

The client is now listed our documentation as [unofficial 3rd party client](https://github.com/zalando/shop-api-documentation/wiki/Zalando-Shop-API-3rd-party-clients). There is also a [google group](https://groups.google.com/forum/#!forum/zalando-api) now for developers and users of the Zalando Shop API. Feel kindly invited to subscribe to this group in order to keep up to date regarding API changes.

Kind regards Uwe

**Comment by cschalenborgh** [comment]
Thanks Jukey, will do!
