### ISSUE TITLE
Search articles in multiple categories

### ISSUE THREAD

**Issue by cschalenborgh** [zalando/shop-api-documentation#7]
Using https://github.com/zalando/shop-api-documentation/wiki/Articles, is it also possible to search in multiple categories with 1 API request?

**Comment by benjaminwagner** [comment]
Sure. Every filter that is marked as `multiValue: true` can be use in an `/articles` and `/facets` request multiple times. Just look into the `/filters` endpoint.

Example for multi categories search:

https://api.zalando.com/articles?category=mens-clothing-jeans-loose-fit&category=womens-tennis-shoes
