### ISSUE TITLE
Bad request on search for an existent product

### ISSUE THREAD

**Issue by GuillermoBlasco** [zalando/shop-api-documentation#8]
Dear Zalando team,

We are running on some issues with the search endpoint. Consider the product with article id `ke2-m05-0021-05`. We can query the article with:

`https://api.zalando.com/articles/ke2-m05-0021-05`

And the info is shown as it should be. But if we query:

`https://api.zalando.com/articles?articleId=ke2-m05-0021-05`

Then we get a 400 bad request:

```
{
    status: 400,
    message: "validation errors",
    errors: [{
        name: "articleId",
        invalidValues: [
            "ke2-m05-0021-05"
        ],
        invalidName: false
    }]
}
```

Best regards.

**Comment by arekdziewonski** [comment]
Hi Guillermo,

thank you for your question. Rules for articleId have changed over time and I can see this filter still expects the first and last character to be either a capital letter or a digit, despite that in the response we send it in the lowercase. As a workaround you can send articleId in uppercase, e.g. `https://api.zalando.com/articles?articleId=KE2-M05-0021-05`

Kind regards,
Arkadiusz

**Comment by benjaminwagner** [comment]
We updated our parameter validation. Filter with lowercased articleId is working now as expected.
