### ISSUE TITLE
Link to API Endpoint Reference gives 404

### ISSUE THREAD

**Issue by apaatsio** [zalando/shop-api-documentation#9]
On the page https://github.com/zalando/shop-api-documentation/wiki/Api-introduction there is a link to https://api.zalando.com/docs/index.html (API Endpoint Reference). Clicking the link gives 404.

**Comment by jukey** [comment]
Hi @apaatsio the paragaph was updated und contains now links to the swagger documentation and schema:

* https://github.com/zalando/shop-api-documentation/wiki/Api-introduction#schema

Kind regards Uwe
